name: day2-scm-resourcesapi

on:
  push:
    branches:
      - master
    paths:
      - day2/apps/infrastructure/bicep/scm-resourcesapi.bicep
      - day2/apps/dotnetcore/Scm.Resources/**
      - .github/workflows/day2-scm-resourcesapi.yml

  pull_request:
    branches:
      - master
    paths:
      - day2/apps/infrastructure/bicep/scm-resourcesapi.bicep
      - day2/apps/dotnetcore/Scm.Resources/**
      - .github/workflows/day2-scm-resourcesapi.yml

  workflow_dispatch:

env:
  NEED_DEPLOY: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_PACKAGE_PATH: 'publish/scmresourcesapi'
      RESIZER_PACKAGE_PATH: 'publish/resizer'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Transpile bicep files
        run: az bicep build -f ./day2/apps/infrastructure/bicep/scm-resourcesapi.bicep

      - name: Archive ARM Templates artifacts
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: bicep
          path: ./day2/apps/infrastructure/bicep/scm-resourcesapi.json
          retention-days: 30
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Build and publish SCM Resources API
        working-directory: ./day2/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.Api
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './${{ env.API_PACKAGE_PATH }}'

      - name: Archive api dotnetcore package artifacts
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: scmresourcesapi
          path: './day2/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.Api/${{ env.API_PACKAGE_PATH }}/'
          retention-days: 30

      - name: Build and publish SCM ImageResizer
        working-directory: ./day2/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.ImageResizer
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o './${{ env.RESIZER_PACKAGE_PATH }}'

      - name: Archive ImageResizer dotnetcore package artifacts
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: imageresizer
          path: './day2/apps/dotnetcore/Scm.Resources/Adc.Scm.Resources.ImageResizer/${{ env.RESIZER_PACKAGE_PATH }}/'
          retention-days: 30

  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: day2-scm-dev
    needs: build
    if: env.NEED_DEPLOY == 'true'
    env:
      RESOURCE_GROUP_NAME: rg-scm-devday2
      RESOURCE_GROUP_LOCATION: westeurope
      ENV_NAME: devd2
    
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create ResourceGroup if it does not exist
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            if $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
              echo "Azure resource group created"
            fi

      - name: Download bicep artifacts
        uses: actions/download-artifact@v2
        with:
          name: bicep

      - name: Deploy infrastructure to dev environment
        uses: azure/arm-deploy@v1
        id: infrastructure
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./scm-resourcesapi.json
          parameters: env=${{ env.ENV_NAME }} sku=B1

      - name: Download scmresourcesapi artifacts
        uses: actions/download-artifact@v2
        with:
          name: scmresourcesapi
          path: ./scmresourcesapi

      - name: Deploy SCM Resources API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.infrastructure.outputs.resourceApiWebAppName }}
          package: ./scmresourcesapi

      - name: Download imageresizer artifacts
        uses: actions/download-artifact@v2
        with:
          name: imageresizer
          path: ./imageresizer

      - name: Deploy ImageResizer Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ steps.infrastructure.outputs.imageResizerFunctionName }}
          package: ./imageresizer

  deploy-to-test:
    runs-on: ubuntu-latest
    environment: day2-scm-test
    needs: deploy-to-dev
    if: env.NEED_DEPLOY == 'true'
    env:
      RESOURCE_GROUP_NAME: rg-scm-testday2
      RESOURCE_GROUP_LOCATION: westeurope
      ENV_NAME: testd2
    
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create ResourceGroup if it does not exist
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            if $(az group exists --name ${{ env.RESOURCE_GROUP_NAME }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location ${{ env.RESOURCE_GROUP_LOCATION }}
              echo "Azure resource group created"
            fi

      - name: Download bicep artifacts
        uses: actions/download-artifact@v2
        with:
          name: bicep

      - name: Deploy infrastructure to dev environment
        uses: azure/arm-deploy@v1
        id: infrastructure
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./scm-resourcesapi.json
          parameters: env=${{ env.ENV_NAME }} sku=B1

      - name: Download scmresourcesapi artifacts
        uses: actions/download-artifact@v2
        with:
          name: scmresourcesapi
          path: ./scmresourcesapi

      - name: Deploy SCM Resources API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.infrastructure.outputs.resourceApiWebAppName }}
          package: ./scmresourcesapi

      - name: Download imageresizer artifacts
        uses: actions/download-artifact@v2
        with:
          name: imageresizer
          path: ./imageresizer

      - name: Deploy ImageResizer Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ steps.infrastructure.outputs.imageResizerFunctionName }}
          package: ./imageresizer