name: day3-scm-searchapi

on:
  push:
    branches:
      - master
    paths:
      - day3/apps/infrastructure/bicep/search/**
      - day3/apps/dotnetcore/Scm.Search/**
      - .github/workflows/day3-scm-search.yml

  pull_request:
    branches:
      - master
    paths:
      - day3/apps/infrastructure/bicep/search/**
      - day3/apps/dotnetcore/Scm.Search/**
      - .github/workflows/day3-scm-search.yml

  workflow_dispatch:

env:
  API_PACKAGE_NAME: "scmsearchapi.zip"
  INDEXER_PACKAGE_NAME: "indexer.zip"
  BICEP_FILE_NAME: "searchmain.bicep"

jobs:
  build-bicep:
    if: github.repository == 'azuredevcollege/trainingdays'
    runs-on: ubuntu-latest
    env:
      BICEP_FILE_PATH: "./day3/apps/infrastructure/bicep/search/searchmain.bicep"
      BICEP_MODULE_PATH: "./day3/apps/infrastructure/bicep/search/"
      NEED_DEPLOY: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Transpile bicep files
        run: az bicep build -f ${{ env.BICEP_FILE_PATH }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: drop
          path: ${{ env.BICEP_MODULE_PATH }}
          if-no-files-found: error
          retention-days: 30

  build-api:
    if: github.repository == 'azuredevcollege/trainingdays'
    runs-on: ubuntu-latest
    env:
      API_PROJECT_PATH: "./day3/apps/dotnetcore/Scm.Search/Adc.Scm.Search.Api"
      API_PACKAGE_PATH: "publish/scmsearchapi"
      NEED_DEPLOY: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: "~/.nuget/packages"
          key: ${{ runner.os }}-nuget-${{ hashFiles('./day3/apps/dotnetcore/Scm.Search/Adc.Scm.Search.Api/packages.lock.json') }}

      - name: Build and publish SCM Search API
        working-directory: ${{ env.API_PROJECT_PATH }}
        run: |
          dotnet restore --locked-mode
          dotnet build --configuration Release
          dotnet publish -c Release -o './${{ env.API_PACKAGE_PATH }}'

      - name: Zip SCM Search API
        working-directory: ${{ env.API_PROJECT_PATH }}/${{ env.API_PACKAGE_PATH }}
        run: |
          zip -r ${{ env.API_PACKAGE_NAME }} ./*

      - name: Archive api dotnetcore package artifacts
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: drop
          path: "${{ env.API_PROJECT_PATH }}/${{ env.API_PACKAGE_PATH }}/${{ env.API_PACKAGE_NAME }}"
          if-no-files-found: error
          retention-days: 30

  build-indexer:
    if: github.repository == 'azuredevcollege/trainingdays'
    runs-on: ubuntu-latest
    env:
      INDEXER_PROJECT_PATH: "./day3/apps/dotnetcore/Scm.Search/Adc.Scm.Search.Indexer"
      INDEXER_PACKAGE_PATH: "publish/indexer"
      NEED_DEPLOY: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Use Cache
        uses: actions/cache@v2
        with:
          path: "~/.nuget/packages"
          key: ${{ runner.os }}-nuget-${{ hashFiles('./day3/apps/dotnetcore/Scm.Search/Adc.Scm.Search.Indexer/packages.lock.json') }}

      - name: Build and publish Indexer
        working-directory: ${{ env.INDEXER_PROJECT_PATH }}
        run: |
          dotnet restore --locked-mode
          dotnet build --configuration Release
          dotnet publish -c Release -o './${{ env.INDEXER_PACKAGE_PATH }}'

      - name: Zip Indexer
        working-directory: ${{ env.INDEXER_PROJECT_PATH }}/${{ env.INDEXER_PACKAGE_PATH }}
        run: |
          zip -r ${{ env.INDEXER_PACKAGE_NAME }} ./*

      - name: Archive indexer artifacts
        uses: actions/upload-artifact@v2
        if: env.NEED_DEPLOY == 'true'
        with:
          name: drop
          path: "${{ env.INDEXER_PROJECT_PATH }}/${{ env.INDEXER_PACKAGE_PATH }}/${{ env.INDEXER_PACKAGE_NAME }}"
          if-no-files-found: error
          retention-days: 30

  deploy-infrastructure-to-dev:
    if: (github.repository == 'azuredevcollege/trainingdays') && ((github.event_name == 'push') || (github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    environment: day3-scm-dev
    needs: [build-bicep, build-api, build-indexer]
    outputs:
      resourceGroupName: ${{ steps.createResourceGroupName.outputs.name }}
      searchApiWebAppName: ${{ steps.infrastructure.outputs.searchApiWebAppName }}
      indexerFunctionName: ${{ steps.infrastructure.outputs.indexerFunctionName }}

    env:
      RESOURCE_GROUP_NAME: rg-scm-devday3
      RESOURCE_GROUP_LOCATION: westeurope
      ENV_NAME: devd3

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Create ResourceGroup name
        id: createResourceGroupName
        run: echo "::set-output name=name::${{ env.RESOURCE_GROUP_NAME }}-${{ env.GITHUB_REPOSITORY_OWNER_PART }}"

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create ResourceGroup
        run: >
          az group create
          -l ${{ env.RESOURCE_GROUP_LOCATION }}
          -n ${{ steps.createResourceGroupName.outputs.name }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: drop

      - name: Deploy infrastructure to dev environment
        uses: azure/arm-deploy@v1
        id: infrastructure
        with:
          failOnStdErr: false
          resourceGroupName: ${{ steps.createResourceGroupName.outputs.name }}
          template: ./${{ env.BICEP_FILE_NAME }}
          parameters: env=${{ env.ENV_NAME }}

  deploy-searchapi-to-dev:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure-to-dev

    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: drop

      - name: Deploy SCM Search API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.deploy-infrastructure-to-dev.outputs.searchApiWebAppName }}
          package: ./${{ env.API_PACKAGE_NAME }}

  deploy-indexer-to-dev:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure-to-dev

    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: drop

      - name: Deploy Indexer Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.deploy-infrastructure-to-dev.outputs.indexerFunctionName }}
          package: ./${{ env.INDEXER_PACKAGE_NAME }}

      - name: Sync function triggers
        run: >
          az rest --method POST 
          --url https://management.azure.com/subscriptions/${{fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId}}/resourceGroups/${{ needs.deploy-infrastructure-to-dev.outputs.resourceGroupName }}/providers/Microsoft.Web/sites/${{ needs.deploy-infrastructure-to-dev.outputs.indexerFunctionName }}/syncfunctiontriggers?api-version=2020-12-01

  deploy-infrastructure-to-test:
    if: (github.repository == 'azuredevcollege/trainingdays') && ((github.event_name == 'push') || (github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    environment: day3-scm-test
    needs: [deploy-searchapi-to-dev, deploy-indexer-to-dev]
    outputs:
      resourceGroupName: ${{ steps.createResourceGroupName.outputs.name }}
      searchApiWebAppName: ${{ steps.infrastructure.outputs.searchApiWebAppName }}
      indexerFunctionName: ${{ steps.infrastructure.outputs.indexerFunctionName }}

    env:
      RESOURCE_GROUP_NAME: rg-scm-testday3
      RESOURCE_GROUP_LOCATION: westeurope
      ENV_NAME: testd3

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Create ResourceGroup name
        id: createResourceGroupName
        run: echo "::set-output name=name::${{ env.RESOURCE_GROUP_NAME }}-${{ env.GITHUB_REPOSITORY_OWNER_PART }}"

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create ResourceGroup
        run: >
          az group create
          -l ${{ env.RESOURCE_GROUP_LOCATION }}
          -n ${{ steps.createResourceGroupName.outputs.name }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: drop

      - name: Deploy infrastructure to test environment
        uses: azure/arm-deploy@v1
        id: infrastructure
        with:
          failOnStdErr: false
          resourceGroupName: ${{ steps.createResourceGroupName.outputs.name }}
          template: ./${{ env.BICEP_FILE_NAME }}
          parameters: env=${{ env.ENV_NAME }}

      - name: Deploy SCM Search API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.infrastructure.outputs.searchApiWebAppName }}
          package: ./${{ env.API_PACKAGE_NAME }}

      - name: Deploy Indexer Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ steps.infrastructure.outputs.indexerFunctionName }}
          package: ./${{ env.INDEXER_PACKAGE_NAME }}

  deploy-searchapi-to-test:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure-to-test

    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: drop

      - name: Deploy SCM Search API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.deploy-infrastructure-to-test.outputs.searchApiWebAppName }}
          package: ./${{ env.API_PACKAGE_NAME }}

  deploy-indexer-to-test:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure-to-test

    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: drop

      - name: Deploy Indexer Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.deploy-infrastructure-to-test.outputs.indexerFunctionName }}
          package: ./${{ env.INDEXER_PACKAGE_NAME }}

      - name: Sync function triggers
        run: >
          az rest --method POST 
          --url https://management.azure.com/subscriptions/${{fromJSON(secrets.AZURE_CREDENTIALS).subscriptionId}}/resourceGroups/${{ needs.deploy-infrastructure-to-test.outputs.resourceGroupName }}/providers/Microsoft.Web/sites/${{ needs.deploy-infrastructure-to-test.outputs.indexerFunctionName }}/syncfunctiontriggers?api-version=2020-12-01
