name: Day4 - Common Infrastructure
on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/day4-scm-common.yaml
      - day4/apps/infrastructure/bicep/**
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/day4-scm-common.yaml
      - day4/apps/infrastructure/bicep/**

env:
  RESOURCE_GROUP_NAME_PREFIX: SCM-DEVD4
  TEMPLATE_NAME: commonmain
  LOCATION: WestEurope
  ENVIRONMENT_NAME: dev

jobs:
  arm-template:
    if: ${{ github.repository == 'azuredevcollege/trainingdays' }}
    runs-on: ubuntu-latest
    env:
      TEMPLATE_PATH: day4/apps/infrastructure/bicep/common
    steps:
      - uses: actions/checkout@v2
      - name: Transpile bicep files
        run: az bicep build -f ${{env.TEMPLATE_NAME }}.bicep
        working-directory: ${{ env.TEMPLATE_PATH }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: template
          path: ${{ env.TEMPLATE_PATH }}/${{env.TEMPLATE_NAME }}.json
          if-no-files-found: error
          retention-days: 90

  deploy:
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'azuredevcollege/trainingdays' }}
    runs-on: ubuntu-latest
    needs: arm-template
    environment: day4-scm-dev
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Download the arm template
        uses: actions/download-artifact@v2
        with:
          name: template
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create resource group
        run: >
          az group create
          -l ${{ env.LOCATION }}
          -n ${{ env.RESOURCE_GROUP_NAME_PREFIX }}-${{ env.GITHUB_REPOSITORY_OWNER_PART }}
      - name: Deploy Azure Resource Manager (ARM) template
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME_PREFIX }}-${{ env.GITHUB_REPOSITORY_OWNER_PART }}
          template: ${{env.TEMPLATE_NAME }}.json
          deploymentMode: Incremental
          parameters: >
            env=${{ env.ENVIRONMENT_NAME }}
